### ISSUE TITLE
Floating islands

### ISSUE THREAD

**Issue by CrysKilljoy** [Builderb0y/BigGlobe#14]
I'm like 80% sure that this is caused by Big Globe, as I have no other World Gen mod installed. It generates floating Islands, which are causing problems with shaders and distant horizon, I guess. 

Would be great to just add a toggle for floating islands

[2024-09-26_22 53 36](https://github.com/user-attachments/assets/03de0070-5ada-455c-9f95-cee73c2676a3)

[latest.log](https://github.com/user-attachments/files/17155937/latest.log)

**Comment by Builderb0y** [comment]
Those are an intentional feature, and there's useful resources you can get from them that can otherwise only be found in the end dimension. The fact that shaders and Distant Horizons handles them so poorly is not really my fault.

**Comment by nmurphy101** [comment]
@CrysKilljoy In distant horizons advanced settings there's a cave culling setting that you can change to 0 that will solve this issue.

**Comment by feetbots** [comment]
Would that affect performance much?
