### ISSUE TITLE
Can we contact on discord?

### ISSUE THREAD

**Issue by trewqaGGG** [Builderb0y/BigGlobe#15]
My discord username is: `12233201`

First off I would like to say I am a huge fan of your mod ever since I saw it be showcased on AHS's video. I have many ideas, but the biggest ones will definitely be:
Having temperature and humidity be dependent on a number of user-configurable variables, by default maybe temperature be dependent on the Z axis, and humidity be dependent on the X axis. The temperature/humidity gradient could go on forever or could loop back depending on an option, OR you could take the amazing route and have it depend dynamically on the topography/water bodies, and have rivers depend on this as well. It would be a LOT of hard work but I would like to see this mod become an all-encompassing world/ecology-sim mod (the first of its kind) where every factor of the world—rivers, biomes, topography, climate, etc. would all be dynamic and change naturally over time or via the players' actions.

![image](https://github.com/user-attachments/assets/184df113-03c9-4465-8173-c769bc80f395)

That's alot to take in for now so just consider adding temperature/humidity banding on top of the bucket list for now. I would really like to see that happen ASAP. Next would probably be making the continents and landmasses all be realistic looking from a bird's eye standpoint, like something from a well-made fantasy map rather than randomly generated videogame noise. That includes having massive variance in the heights of different parts of the world, where you have low areas like the Afar Triangle in East Africa and high areas like the Tibetan or Mongolian plateaus, but also extremities like the Himalayas, the Alps, or the Urals, etc. Did I mention I'm sort of a geography nerd?

And for climate it would be making it all dynamic and dependent on the topography and water bodies, and also making the water bodies be dependent on the topography and so forth.

Anyway I am a big fan of this mod and would like to see it grow into something leagues more beautiful than it already is. In my opinion, barring all the current inconveniences of this mod, it blows other existing terrain gen mods out of the water, like BOP, terralith, OTBYG, tectonic, etc.

**Comment by Builderb0y** [comment]
Temperature dependent on the z position is already possible with a data pack. As is anything else you can describe via a stateless mathematical system which takes position and world seed as its sole input. I'm not going to be making worldgen respond to player actions or time, since minecraft doesn't periodically re-generate chunks, and this would also violate the stateless nature of how my terrain gen system is currently setup.

**Comment by trewqaGGG** [comment]
Also put the mod on curseforge. Way more users use the platform and it should be done no matter your views on the website's history, visibility is crucial to maintain motivation!

**Comment by Builderb0y** [comment]
Not really. I've been developing this mod since 1.12.2 with hardly anyone caring about it. I'm motivated to continue working on it because I like working on it. If anything, having it become so popular so quickly has been de-motivating for a bunch of reasons that I'm not going to elaborate on here.

**Comment by trewqaGGG** [comment]
You're right and I felt the same about things before, this project is your pet and it would have been better to see it grow on your own accord, rather than some popular YouTuber half-assedly glossing over it causing your mod to grow so suddenly without your knowing.
