### ISSUE TITLE
Doesn't work with dynamic surroundings 

### ISSUE THREAD

**Issue by Drfreeman1488** [Builderb0y/BigGlobe#16]
Whenever I enter any biome, the ambient sounds don't play at all. Only sounds like toolbar switching or reverb, other than a few other sounds, the world is incredibly dead. I think this is due to the mod not recognizing big globe biomes.

**Comment by Builderb0y** [comment]
That is probably why, yeah. DS looks like it can be [configured](https://github.com/OreCruncher/DynamicSurroundingsFabric/blob/main/src/main/resources/assets/dsurround/dsconfigs/biomes.json) to detect modded biomes, and it *might* be possible to have compatibility [built-in](https://github.com/OreCruncher/DynamicSurroundingsFabric/tree/main/src/main/resources/assets/dsurround/dsconfigs/tags/worldgen/biome) to big globe. But it also says the current format is unstable and un-documented. Maybe I'll make a compatibility addon for it eventually, assuming no one else makes one first.

**Comment by Drfreeman1488** [comment]
I would appreciate it if you did make a patch for it. I'm going to see if I can add the biomes to the JSON by myself and see if it works

**Comment by Drfreeman1488** [comment]
I tried adding them through the JSON and it didn't work, no sounds as usual

**Comment by trewqaGGG** [comment]
Oof, your problem resolves soon. I use ambientsounds instead of Dynamic Surroundings

**Comment by Drfreeman1488** [comment]
If it helps, putting the biome names inside the mods file did not work, perhaps something in the parentheses could work but there are a lot of moving parts in this mod.
![image_2024-09-28_171946250](https://github.com/user-attachments/assets/3e99d3af-30be-471b-8063-09bf116a9f70)

**Comment by Builderb0y** [comment]
I doubt that's valid syntax to have two `&&`'s next to each other like that. And also a biome can't simultaneously be two other biomes, so that should probably use `||` instead of `&&`.

**Comment by Drfreeman1488** [comment]
> I doubt that's valid syntax to have two `&&`'s next to each other like that. And also a biome can't simultaneously be two other biomes, so that should probably use `||` instead of `&&`.

Aah, I apologize, but I haven't done a lot of coding in my life

**Comment by Builderb0y** [comment]
Dynamic Surroundings claims to use Nashorn's JS engine, so if you can learn a little bit of JS syntax, it would probably help for adding compatibility.

**Comment by Drfreeman1488** [comment]
I have managed to add compatibility, at the very least for the temperate forest, I haven't tried any of the other biomes yet but from the ones I could find I did add them. All I did was copy one of the recent patches made by the dev for another mod replace the biomes in there with the Big Globe biomes and change some traits, I think I got most of the biomes in Big Globe but I do believe I missed a few.

[bigglobe.zip](https://github.com/user-attachments/files/17535643/bigglobe.zip)

**Comment by Builderb0y** [comment]
Neat!

**Comment by Drfreeman1488** [comment]
New issue, seems that the ambiance stops after a long distance traveled. I'm trying to figure out why

**Comment by Drfreeman1488** [comment]
https://github.com/user-attachments/assets/8ccc7187-415b-49e5-9886-1cda17852ac4

It seems at a certain height it starts working again, but below 50 it stops

**Comment by Builderb0y** [comment]
Dynamic surroundings might be assuming the sea level will always be at Y 64. If this is the case, then there's not much I can do about that. Big globe's sea level is at Y 0.

**Comment by Drfreeman1488** [comment]
https://files.catbox.moe/q59qfi.7z

It's fully compatible, there are some biomes I think are missing but other than that everything works as intended. Thank you for your help in the debugging, feel free to share it. The link contains the JAR file


Also, I've noticed villages aren't spawning. Is that part of the mod?

**Comment by Builderb0y** [comment]
Villages *should* spawn, though it's always possible that I broke something with them again.

**Comment by Drfreeman1488** [comment]
I've found sand temples and witch houses as well as individual houses but not a single village

**Comment by Builderb0y** [comment]
Villages were fixed in V4.7.0, and now V4.8.0 is also available. I just forgot to close this issue at the time.
