### ISSUE TITLE
compatibility 

### ISSUE THREAD

**Issue by TaarKaRaja** [Builderb0y/BigGlobe#17]
I really love this mod and it has really cool and unique features that other world generation mods have not thought of. It'd be nice to play with some other mods so could you please if you don't mind provide a link to data packs that are compatible with this mod so that ores such as from create or structures such as from cataclysm can generate?

**Comment by Builderb0y** [comment]
As stated on modrinth, none of the addon packs currently in existence have been updated in a long time, and they probably don't work anymore. So really there aren't any packs I can link you to.
