### ISSUE TITLE
is NeoForge/Forge version planned ?

### ISSUE THREAD

**Issue by AlphaCentauri3D** [Builderb0y/BigGlobe#18]
With this mod, mining ores in tech mods would become truly exciting

**Comment by Builderb0y** [comment]
No, but you can use Sinytra Connector for that. Right now it *mostly* works. Just need to disable `MobSpawnerLogic_SpawnLightning` in `.minecraft/config/bigglobe/mixins.properties`. A future version will (hopefully) fix the issue requiring this mixin to be disabled in the first place.

**Comment by AlphaCentauri3D** [comment]
> No, but you can use Sinytra Connector for that. Right now it _mostly_ works. Just need to disable `MobSpawnerLogic_SpawnLightning` in `.minecraft/config/bigglobe/mixins.properties`. A future version will (hopefully) fix the issue requiring this mixin to be disabled in the first place.

thanks
