### ISSUE TITLE
Crash on 1.20.1

### ISSUE THREAD

**Issue by Martmists-GH** [Builderb0y/BigGlobe#2]
Log: https://mclo.gs/ldKIjeL

**Comment by Builderb0y** [comment]
I can't seem to reproduce this issue with your version of minecraft, fabric, and big globe. Does this issue still happen with ONLY fabric and big globe installed?

**Comment by Martmists-GH** [comment]
After some testing, it seems to be caused by [Alloy Forgery](https://github.com/wisp-forest/alloy-forgery/) being added. I'll open an issue on their repo as well, as I don't know which mod is the cause.

**Comment by Builderb0y** [comment]
Hopefully fixed in [V3.11.2](https://modrinth.com/mod/big-globe/version/1Ts7AzqD).

**Comment by Builderb0y** [comment]
If there's no further comments or complaints, then I'm going to assume the fixed version works.
