### ISSUE TITLE
How could this work with Aternos

### ISSUE THREAD

**Issue by konspat** [Builderb0y/BigGlobe#20]
Im trying to get this to work with aternos but i dont seem to have found it yet

**Comment by Builderb0y** [comment]
I don't know what that is, and it doesn't seem to have a page on modrinth.

**Comment by konspat** [comment]
> I don't know what that is, and it doesn't seem to have a page on modrinth.

its a server hosting site for minecraft thats free so its really limited but it does have you mod 
https://aternos.org/:en/ this is the site

**Comment by ghost** [comment]
> its a server hosting site for minecraft thats free so its really limited but it does have you mod https://aternos.org/:en/ this is the site

I'm highly sure this page is for reporting issues about the mod. Install the mod on Aternos and change the world generator type, and if the mod isn't there, you'll have to request it.

**Comment by Builderb0y** [comment]
If aternos gives you access to `server.properties`, set `level-type` to `bigglobe\:bigglobe`. If aternos does not give you access to `server.properties`, then there's nothing I can do here other than recommend a different hosting service.

**Comment by trewqaGGG** [comment]
Thanks, I was looking for this answer two days ago. It was only by heavenly grace that a github issue popped up the next day answering this.
