### ISSUE TITLE
Structures floating

### ISSUE THREAD

**Issue by Minecraft69er** [Builderb0y/BigGlobe#21]
I found two structures so far that are floating. One was an archeology site sticking out the side of a mountain, and the other is a pillager outpost. I have attached an image of the pillager outpost. ( This is my first time doing this so if the image doesn't appear, I apologize)
![2024-09-28_14 44 44](https://github.com/user-attachments/assets/677225ea-9436-4e2f-9998-627ca5fcd645)

**Comment by Builderb0y** [comment]
The trail ruins... yeah I don't think I check for hilly terrain or bury them properly. Something for me to decide how to handle eventually. The pillager outpost might be related to the lava lake I can see in the background. Those are known to cause other similar issues like #11.

**Comment by Builderb0y** [comment]
Structures which spawn on top of lakes will, as of V4.4.0, create hills under them instead of floating.
