### ISSUE TITLE
compatibility all the fabric 7

### ISSUE THREAD

**Issue by ky6200** [Builderb0y/BigGlobe#23]
which mods are incompatible with big globe?

**Comment by Builderb0y** [comment]
I don't have a list. Anything related to worldgen will either do nothing in big globe worlds, prevent you from creating big globe worlds, or mess up inside big globe worlds. With an incredibly tiny chance of actually working properly. Anything which doesn't touch worldgen will *probably* work fine. If you find a mod which isn't worldgen-related and also doesn't work with big globe, feel free to report it here.
