### ISSUE TITLE
i need help with this mod

### ISSUE THREAD

**Issue by skellysit** [Builderb0y/BigGlobe#24]
so pretty much i love this mod i love the underground and the nether but i dont like the surface and i want to make it so the surface is the vanilla surface because i want to uses Tectonic mod for the surface but keep the underground and nether from the big globe mod i also want structures from other mods to be compatible like yungs better. But pretty much i want to make the surface the Tectonic mod and to remove all structures from the big globe mod and make other structure mod compatible i just want the underground and the nether. thank you if you know how to fix this i am making a modpack

**Comment by Builderb0y** [comment]
Not possible to use multiple chunk generators for the same world.
