### ISSUE TITLE
Just want to know if im allowed to use this in a pack that would be published on CurseForge

### ISSUE THREAD

**Issue by Avar-Nyx** [Builderb0y/BigGlobe#28]
Me and a friend are working on a Create based pack and i wanted to know if i could use this mod as the terrain gen mod, we would love to use it in the modpack.
<3
-The RTK team

**Comment by Builderb0y** [comment]
I'm not super familiar with how curseforge modpacks work. Would this require re-uploading Big Globe to curseforge?

**Comment by Fleischboss** [comment]
Hello, this mod seems great! Would there be anything speaking against uploading it to curseforge, as I was looking to publish a modpack with this as well.

**Comment by Builderb0y** [comment]
I don't want big globe uploaded to curseforge as its own project. Embedding it inside a modpack file is acceptable, but the best option would be putting a URL in the modpack file which points to modrinth.
