### ISSUE TITLE
Incompatibility with Worldedit

### ISSUE THREAD

**Issue by Arthurmeade12** [Builderb0y/BigGlobe#3]
Any help is appreciated.
~~https://mclo.gs/bY3q2JD~~

Edit: This appears to be an incompatibility with Worldedit.
https://mclo.gs/6RwvNOe

**Comment by Builderb0y** [comment]
Your log file says you are using worldedit 7.3.0-beta-03 and MC 1.20.1 at the same time. Curseforge says that worldedit 7.3.0-beta-03 is only for MC 1.20.4. Do you have the wrong version installed? 7.2.15 seems to work fine for me.

**Comment by Arthurmeade12** [comment]
Sorry for my mistake. Thanks.
