### ISSUE TITLE
A few requests

### ISSUE THREAD

**Issue by thepacksmith** [Builderb0y/BigGlobe#30]
Firstly, I would like to say this is easily the most impressive world gen mod I have ever seen.

I have a few requests I would love to see:

NeoForge compatibility (+ CurseForge upload) - This has probably already been requested, but this would be a fantastic thing for the community. Sinytra Connector is definitely an option, but it can cause some weird oddities with some mods and can make a modpack unstable. This mod has huge modpack potential.

A separate worldgen-only version - No additional blocks, fully vanilla palette (except for the molten rock, as it makes sense for the world depth). No custom structures. No hyperspace. No custom biomes. No new items. Just overworld surface generation (using the custom noise of this mod but with vanilla biomes + modded compat), world height adjustments, cave changes. Same thing for the nether/end. This worldgen-only version will unlock a whole new level of possibilities for pack developers.

I hope you consider these changes, and I understand it would take time.

**Comment by Builderb0y** [comment]
All of these requests have been considered and rejected in the past. Forge compatibility doubles the number of versions and source sets I have to maintain. I don't like using curseforge and I don't want my mods to be hosted there. Butchering the mod to remove literally all of its actual content is not something I want to do, nor do I want others to do it except for personal use. Using vanilla biomes would not even restore mod compatibility anyway. You'd still need a data pack for modded biomes and features. All it would do is make modded structures spawn in big globe worlds, probably at the wrong Y level, and probably looking horrifically out-of-place.

**Comment by thepacksmith** [comment]
I understand. Thank you for reading through anyway.
