### ISSUE TITLE
Mod ore spawn

### ISSUE THREAD

**Issue by MrCroller** [Builderb0y/BigGlobe#32]
Hello. Trying your mod, really like the idea of expanding the world.
Trying to play with friends on the server where the mod Create. Unfortunately a very important component for it, namely zinc, not spawn.
Is there any way to add its spawn and customize it?

> Also wanted to clarify off topic, are you planning to port the mod to Forge and add customization like: (leave vanilla surface, change depths, hell, end)?

**Comment by Builderb0y** [comment]
Modded ores can be added with a data pack. I'm working on updating a bunch of my old data packs right now, and plan on releasing them when I re-add the invite to my discord server to my modrinth page. This is currently scheduled to happen on the 26'th. If my page views die down faster than expected, I might do this sooner.

A forge port is not planned. Not entirely sure what you mean with the rest of those customizations.
