### ISSUE TITLE
(Not an Issue) Where to find links for Discord server for compability patches 

### ISSUE THREAD

**Issue by Never23345** [Builderb0y/BigGlobe#33]
Didnt find any invite links , despite it was mentioned about existence of some compabilitiy patches in discord server of mode

**Comment by Builderb0y** [comment]
As stated on my modrinth page,

> The invite to my Discord server has been temporarily removed from Modrinth to prevent an influx of new users from a certain popular YouTuber. And also none of those compatibility packs have been updated in a long time anyway and probably don't work anymore, so you're not missing out on anything by not being there.
