### ISSUE TITLE
Is this mod compatible with mods that put new ores?

### ISSUE THREAD

**Issue by Endri1987-1234567890** [Builderb0y/BigGlobe#34]

**Comment by Builderb0y** [comment]
Only with a data pack. In the case of ores, data packs to add compatibility are reasonably easy to make.

**Comment by Endri1987-1234567890** [comment]
does the datapack maker have to make one for each mod or they can make one for all?
btw idk how to make one

**Comment by Builderb0y** [comment]
You can put all the mods you want to support in the same data pack, but it's not possible to make a data pack which works with all possible mods. I have now written some documentation on the json format of ores [here](https://github.com/Builderb0y/BigGlobe/blob/scriptable-generators/scripting%20docs/files/data/modid/worldgen/configured_feature/Ores.md).
