### ISSUE TITLE
How to disable the mod gen for the Nether and the End, so BetterNether and BetterEnd mods are the only ones that work in there?

### ISSUE THREAD

**Issue by Voidren127** [Builderb0y/BigGlobe#35]
Is there a way to disable BigGlobe's nether and end generation, so that it only effects the overworld, allowing BetterNether and BetterEnd to be the only ones that are active in the nether and end?

**Comment by Builderb0y** [comment]
You will need to create a data pack with a custom world preset which is a combination of big globe's and better nether/end's.

**Comment by Voidren127** [comment]
How does one make that, i have no experience making datapacks

**Comment by Builderb0y** [comment]
General data pack info: https://minecraft.wiki/w/Tutorials/Creating_a_data_pack
Info on world presets specifically: https://minecraft.wiki/w/World_preset_definition
