### ISSUE TITLE
Incompatible with Flashback mod

### ISSUE THREAD

**Issue by Tysos24** [Builderb0y/BigGlobe#36]
If I record a Flashback in a Big Globe world, it ‘disconnects’ me when I try to open it, sending me to the server list. I doubt this issue is much of a priority for the Flashback devs, but I was hoping you might be able to do something for it. I’ve attached the log here.
[latest.log](https://github.com/user-attachments/files/17267594/latest.log)

**Comment by Builderb0y** [comment]
Well, I couldn't get flashback to run in a dev environment, and in a normal environment I get a completely different error than you do. I fixed the error I got already (it was breaking other things too), and after some very heavy investigation of your stack trace, I... might've fixed yours too? I'm honestly not sure. But that's something you can re-test in the next version after I release it.

**Comment by Builderb0y** [comment]
Does V4.5.0 work with flashback? Or is there a new error?

**Comment by Tysos24** [comment]
I'm not sure what the error is, but *something's* causing a problem. So maybe; I have a lot of other mods too.
[latest.log](https://github.com/user-attachments/files/17348794/latest.log)

**Comment by Tysos24** [comment]
So maybe. (I have a lot of other mods)

**Comment by Builderb0y** [comment]
There's a few different errors in there. The first mentions syncing logic, the trinkets mod, and the cardinal components mod. Perhaps flashback doesn't know how to handle custom player data? The 2nd mentions command parsing. Maybe one of your mods or data packs uses mojang's command function system incorrectly? The 3rd is related to the "forge config API port" mod, while doing something with the "pickup notifier" mod's config file or folder. And lastly, there's also an error with replay itself having a null world for some reason. Maybe the world was supposed to be set later and just wasn't set at the time it was needed?

In any case, none of the stack traces in that log file are related to big globe anymore. You can try removing trinkets and/or pickup notifier to see if that improves anything. And if that *doesn't* improve anything, maybe try a binary split search next.

**Comment by Tysos24** [comment]
Thanks for the help!
