### ISSUE TITLE
Constantly take damage while at core y levels?

### ISSUE THREAD

**Issue by flashgnash** [Builderb0y/BigGlobe#38]
At the moment if you dig down to that level it's just unlimited free ore (obviously it's time consuming to get to that point but still)

Could a feature be implemented to have the damage ticks from the core blocks always hit if you're under a certain Y level instead of just when standing on core blocks, and increase in damage/frequency as you descend deeper? (Maybe buffing the rarity of ores generated by pouring water as you get deeper)

Fire protection enchants could greatly reduce this damage to make it livable, maybe negate it entirely if applied to netherite armour

Water could also evaporate after a certain amount of time so if you aren't quick enough to pick it back up you lose it and have to go get more

I believe these things would make the reward a lot more risky and challenging for players

**Comment by Builderb0y** [comment]
The main problem with this is that the core is entirely script-driven. There is no guarantee that the core will exist in worlds created by data packs. And I don't really want to put in the effort to expand my script system enough to do things with entities and blocks after the world has already been generated. Especially when it would require so many different hooks to be general-purpose. You could use minecraft's built-in command function system for player damage though.
