### ISSUE TITLE
Crystalline Prismarine, how to get prismarine crystals and shards?

### ISSUE THREAD

**Issue by Nimjam** [Builderb0y/BigGlobe#39]
Maybe it's just a problem on my site or I'm just stupid, but how do I get Prismarine crystals and shards out of Crystalline Prismarine or is it currently broken?

**Comment by Builderb0y** [comment]
Looks like the loot table format changed in 1.20.5 with the new item component changes and I didn't notice. I'll make sure all the loot tables work correctly in the next version.

**Comment by Builderb0y** [comment]
Should be fixed in V4.5.0. Simply break the block with a pickaxe to get prismarine crystals and shards. Fortune increases the number of crystals, and silk touch gives you the block as-is.
