### ISSUE TITLE
crash from mod

### ISSUE THREAD

**Issue by keganpowers34** [Builderb0y/BigGlobe#40]
[crash-2024-10-09_23.28.59-server.txt](https://github.com/user-attachments/files/17319933/crash-2024-10-09_23.28.59-server.txt)

**Comment by keganpowers34** [comment]
happened when entering void dimension

**Comment by Builderb0y** [comment]
That crash log doesn't mention any of my code. Or any other mod's code, for that matter. It seems to be a vanilla bug (unlikely), or a bug in a mod which mixes into vanilla code (more likely). I wasn't able to reproduce this issue even with a couple of the optimization mods you have installed that I thought might be likely to touch the classes where the crash occurred. Does this issue happen for you with *only* big globe installed? if not, you might want to try a binary split search to figure out which mod is incompatible.

Also, what do you mean by void dimension? Are you referring to hyperspace? I tested hyperspace too just now, and had no crash there either.

**Comment by keganpowers34** [comment]
im guessing it has to do with one or more of the performance mods installed on the server. it hasn't happened again so im going to close the issue
