### ISSUE TITLE
rivers look really bad and form really bad

### ISSUE THREAD

**Issue by texas2mrw** [Builderb0y/BigGlobe#43]
hey developer you gotta fix your rivers man. they dont just flow like this
![bild_2024-10-13_113900198](https://github.com/user-attachments/assets/32ccc4a6-30ae-4dc9-9f5c-e8f19e9d787c)
its going all over everywhere. you should make waterfalls and stones getting in the way of the water. and if it goes up like this it should also end at the top of a mountain somewhere.

**Comment by texas2mrw** [comment]
![image](https://github.com/user-attachments/assets/5ed413d4-43b0-40be-b436-507f7bf5d157)

**Comment by Builderb0y** [comment]
Making rivers that look good is not at all trivial when you're restricted to generating terrain statelessly and dependency-less-ly. The rivers I have are about as good as you can hope for unless you have some magic way to do them that I hadn't thought of before.

**Comment by Builderb0y** [comment]
I'll take that silence to mean you don't have a better magic way to do them.
