### ISSUE TITLE
Placing blocks in hyperspace bricks game

### ISSUE THREAD

**Issue by sam-k0** [Builderb0y/BigGlobe#44]
Apparently, placing blocks in hyperspace makes the game crash.
Once you try re-entering hyperspace after a block has been placed, the game will freeze.

Tested with mods:
- Big Globe
- Concurrent Chunk Management Engine
- Distant Horizons
- Iris
- Just Enough Items
- Sodium
- Xaeros Minimap
- Xaeros Worldmap

Minecraft 1.21.1 on Linux Kernel ver. 5.15

**Comment by Builderb0y** [comment]
Can't reproduce with any of the mods from your list that are likely to have issues with hyperspace. Can you try sampling with visualVM to see what's causing the freeze?
1. Launch minecraft and visualVM, and load the frozen world.
2. Double click anything that looks minecraft-related on the left hand side of the visualVM window.
3. Go to the sampling tab, and start CPU sampling.
4. Wait for 10-30 seconds.
5. Click stop, then snapshot.
6. Save the snapshot as a file, and upload it here for me to take a look at. This will tell me what minecraft is working on while it's frozen.

**Comment by sam-k0** [comment]
I just did the same stuff again that I did before, and this time it doesn't crash.
Maybe it was too much to handle with high render range and distant horizons trying to build caches?
I doubt its anything related to your mod then.
If the problem arises again, I will certainly run visualvm alongside and tell you the results.
