### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by kombq** [Builderb0y/BigGlobe#45]
After watching some videos about this mod, i really liked it, but i have a question, do i need any datapacks for it to expand it, or all the biomes and world generations present in 1 zip or etc. If i need datapack, where i can download it?

**Comment by Builderb0y** [comment]
Additional data packs are only required for making other mods generate stuff inside big globe worlds. Big globe has its own generation built-in.

**Comment by kombq** [comment]
Ok, thanks for replying

вт, 15 окт. 2024 г., 01:28 Builderb0y ***@***.***>:
