### ISSUE TITLE
Sky Islands

### ISSUE THREAD

**Issue by Rocky543211** [Builderb0y/BigGlobe#49]
![2024-10-15_10 14 25](https://github.com/user-attachments/assets/6ada6a10-57bf-4647-8a98-c2c4b6323e3b)

I never saw them in a preview or something similar are they intended or is there a problem somewhere that i missed

**Comment by Builderb0y** [comment]
Skylands are an intended feature, yes. DH just doesn't handle them well. Some people have had better luck with them by setting DH's cave culling height to 0. The latest nightly of DH should contain some changes that improve quality of skylands too.
