### ISSUE TITLE
sulfer usage

### ISSUE THREAD

**Issue by kombq** [Builderb0y/BigGlobe#51]
how to get void bars, and what the hell is sulfure, why i need it

**Comment by Builderb0y** [comment]
Voidmetal ingots can be crafted from iron ingots, ender pearls, and bottled aura. Sulfur can be used as a fuel source in furnaces, and you can use it in a few recipes that normally require coal or charcoal, like torches. I would also recommend using the vanilla recipe book or any other mod that lets you browse recipes, as they would answer your questions a lot faster than github issues will.
