### ISSUE TITLE
Gold feels too rare

### ISSUE THREAD

**Issue by Voidren127** [Builderb0y/BigGlobe#52]
Gold feels like its rarer than diamonds. I know that gold spawns in hot biomes, but when I go mining there I barely find any.
I feel like redstone, gold, and lapis need greatly increased spawn rates if they are only gonna spawn in certain biomes. (Redstone and lapis don't need to be increased that much, as the big veins they spawn in is fine with fortune 3, its just they are very hard to find for some reason, but gold only seems to spawn in small, vanilla sized veins, and is damn near impossible to fine a decent amount of)

Like, I have more diamonds than I do gold, that just feels wrong, espeically when gold tends to be heavily required by other mods.

**Comment by Builderb0y** [comment]
Made them all more common now. That'll be in the next release, but it won't apply retroactively to existing chunks.

**Comment by Voidren127** [comment]
Thanks, I could never find enough.
