### ISSUE TITLE
Как запустить данную генерацию на сервере (что нужно написать в строке "level-type=")

### ISSUE THREAD

**Issue by Giopris** [Builderb0y/BigGlobe#55]

**Comment by Builderb0y** [comment]
Set level-type to "bigglobe\:bigglobe". It should look like this:
```
level-type=bigglobe\:bigglobe
```

**Comment by Giopris** [comment]
Генерация пошла, но после неё сервер крашит с ошибкой: [Worker-Main-11/ERROR] [Big Globe/]: Exception populating noise
[Crash.txt](https://github.com/user-attachments/files/17484909/Crash.txt)

**Comment by Builderb0y** [comment]
That bug was fixed over a year ago. Update to a later version of big globe.

**Comment by Giopris** [comment]
Теперь данная ошибка (если удалить мод, все запускается)
[Crash.txt](https://github.com/user-attachments/files/17485249/Crash.txt)

**Comment by Builderb0y** [comment]
Looks like an incompatibility with alex's caves. It's doing things it absolutely should not be doing, and it probably has no effect in big globe worlds anyway, so I'm not sure why you even have that installed at the same time as big globe, but I guess at the very least I can make it not crash in the next version.

**Comment by Builderb0y** [comment]
The next version has been released. Hopefully it doesn't crash anymore.

**Comment by Builderb0y** [comment]
I assume that silence means it works now.
