### ISSUE TITLE
Cannot launch it with Sinytra Connector 1.21.1 NeoForge on Server

### ISSUE THREAD

**Issue by NoruRama** [Builderb0y/BigGlobe#58]
Was trying to add mod on modded server and try something out but got problem that I cannot launch server with just 2 mods: Big Globe and Sinytra Connector

Was also trying with: 
Connector Extras
Forgified Fabric API

Error Log:
[message.txt](https://github.com/user-attachments/files/17535243/message.txt)

Working Fine in Single Player

**Comment by Builderb0y** [comment]
Should be fixed in a new version of sinytra connector.
