### ISSUE TITLE
Floating islands - again

### ISSUE THREAD

**Issue by Retsom3D** [Builderb0y/BigGlobe#59]
No an issue, but rather a question. Is it possible for me, as a user, to remove the floating islands? The world and world gen looks absolutely stunning, i just dont like floating island.

**Comment by Builderb0y** [comment]
You'll need to make a custom world preset which removes the layer responsible for generating skylands, along with the feature dispatchers which decorate skylands.

**Comment by feetbots** [comment]
How do you create a custom world preset and remove that layer?

**Comment by Builderb0y** [comment]
I would recommend getting familiar with [world presets](https://minecraft.wiki/w/World_preset_definition) and [layers](https://github.com/Builderb0y/BigGlobe/blob/scriptable-generators/scripting%20docs/files/data/modid/worldgen/world_preset/Layers.md) to start with. It'd probably be useful to know how [scripted chunk generators](https://github.com/Builderb0y/BigGlobe/blob/scriptable-generators/scripting%20docs/files/data/modid/worldgen/world_preset/Scripted%20Chunk%20Generators.md) work too. Particularly the reload part.

Edit: I moved some of my documentation files around. The new scriptable chunk generators link is [here](https://github.com/Builderb0y/BigGlobe/blob/scriptable-generators/docs/files/data/modid/worldgen/world_preset/Scripted%20Chunk%20Generators.md).

**Comment by Drexl** [comment]
Came here looking for the same thing. Thanks for getting me started looking in the right direction at least.
