### ISSUE TITLE
"Ambient sounds" mod compatibility

### ISSUE THREAD

**Issue by MottiDowerro** [Builderb0y/BigGlobe#60]
how i can use Ambient sounds with BigGlobe generation?

**Comment by Builderb0y** [comment]
From what I could find on their github, I think you need to override their "regions" files with a resource pack. Take [this file](https://github.com/CreativeMD/AmbientSounds/blob/1.21/src/main/resources/assets/ambientsounds/basic/regions/beach.json) for example; it has a list of biomes at the top. Big Globe's biomes can probably be added to this list. Good luck!

**Comment by MottiDowerro** [comment]
> From what I could find on their github, I think you need to override their "regions" files with a resource pack. Take [this file](https://github.com/CreativeMD/AmbientSounds/blob/1.21/src/main/resources/assets/ambientsounds/basic/regions/beach.json) for example; it has a list of biomes at the top. Big Globe's biomes can probably be added to this list. Good luck!

how can this be done? I don't quite understand..

**Comment by MottiDowerro** [comment]
> From what I could find on their github, I think you need to override their "regions" files with a resource pack. Take [this file](https://github.com/CreativeMD/AmbientSounds/blob/1.21/src/main/resources/assets/ambientsounds/basic/regions/beach.json) for example; it has a list of biomes at the top. Big Globe's biomes can probably be added to this list. Good luck!

I figured it out and it works, but how can I do this as a resource pack?

**Comment by Builderb0y** [comment]
Any files you put in a resource pack get applied on top of what mods provide. So just put the files you want in your resource pack in the same place as they are in the mod, and it should hopefully work.

**Comment by MottiDowerro** [comment]
> Любые файлы, которые вы помещаете в пакет ресурсов, применяются поверх того, что предоставляют моды. Так что просто поместите нужные вам файлы в пакет ресурсов в то же место, где они находятся в моде, и, будем надеяться, это сработает.

IT WORKS, THANK YOU SO MUCH
