### ISSUE TITLE
(Feature Suggestion) Could you add scripting support for ore radius?

### ISSUE THREAD

**Issue by nvalt-1** [Builderb0y/BigGlobe#62]
The purpose of this would be to vary ore size based off a custom script. For example, vein size could be based off of the depth of the ore.

Something like the following:

`"radius": {`
`    "type": "constant",`
`    "value": [`
`        "double min = 3.0L",`
`        "double max = 8.0L",`
`        "double scale = 1024.0L",`
`        "return(mixLinear(min, max, exp2(``bigglobe:approximate_distance_below_surface`` / scale)))"`
`    ]`
`}`

I do not know how difficult this would be to implement on your end, but it would assist in providing more custom behavior when creating compatibility data packs for other mods.

Thanks

**Comment by Builderb0y** [comment]
Done, will be available in the next version. And will be available for everything which uses random sources, not just ore radii:
* Trees:
	* branches > start_frac_y
	* branches > count_per_layer
	* "slanted" trunk type > slant
* Flowers:
	* radius
* Portal temple structure:
	* cracked_chance
* Geodes:
	* radius
	* spikes > commonness
	* spikes > length
	* spikes > crookedness
	* spikes > large_radius
	* spikes > small_radius

Some of these things could in theory attempt to spawn in non-bigglobe worlds, where column values are not available. If the script uses any column values, the feature or structure which uses it will simply do nothing. Though some of these features and structures already require column values and already do nothing outside of big globe worlds.

**Comment by nvalt-1** [comment]
You are a legend. Thank you

**Comment by Builderb0y** [comment]
A new version with scriptable random sources has now been released.
