### ISSUE TITLE
unable to disable generating bigglob structures? 

### ISSUE THREAD

**Issue by Harusarri** [Builderb0y/BigGlobe#63]
I want to disable your structures and end world gen

**Comment by Builderb0y** [comment]
Structures can be disabled by replacing all their types with "noop" with a data pack. Alternatively, you could also empty out the biome tags that they're allowed to spawn in. Either works.

The end dimension can be replaced with the vanilla version or removed entirely with a custom world preset, also provided by a data pack.

**Comment by Harusarri** [comment]
so if I replace into vanilla of end dimention world gen with datapack I can use another terrain gen mod?

**Comment by Builderb0y** [comment]
Using another terrain gen mod for specific dimensions *might* require replacing the end dimension with the other mod's dimension, instead of replacing it with the vanilla version of that dimension. I'd recommend checking if the other mod defines its dimension with a world preset or not.
