### ISSUE TITLE
4.5.0 - Is there a way to add custom feature dispatchers without causing conficts with other Big Globe datapacks?

### ISSUE THREAD

**Issue by nvalt-1** [Builderb0y/BigGlobe#66]
I noticed the docs has a `tag` type for feature dispatchers which sounds like the exact thing I need, but it's for a future version.

Is there a way as of 4.5.0 to add a feature dispatcher without having to override one of the built-in feature dispatcher groups? (small_features, normal_root, etc)

I want to make a compatibility pack containing configured features (not ores/flowers) for one mod, but not have it conflict with another compatibility pack, which means replacing built-in files is a no-go.

If this is not currently possible via datapack, would the upcoming feature dispatcher `tag` type solve this issue?

Thanks

**Comment by Builderb0y** [comment]
The `tag` type was designed specifically because of this exact issue, and I hope to release a version which has it soon.

**Comment by Builderb0y** [comment]
Said version has now been released.
