### ISSUE TITLE
[Request] Datapack/Patch to Add Vanilla Tags to Big Globe

### ISSUE THREAD

**Issue by IanuReeves** [Builderb0y/BigGlobe#67]
Maybe a setting called 'extra mod compat' or something that on world load, assigns vanilla tags in addition to the bigglobe tags so that mods can know wth going on.

ik there are probably many problems with this, especially because of the increased worldheight, so if there is another way to make this work ik alot of people would love this.

Really why I request this is just for antique atlas to work, but this would (in theory) work with structure-modifying mods to actually work

IK its in the change-log that making a data pack for all of them is possible, but there isn't easy access to documentation, and there's no public community to pour in Datapacks created right now since the discord server is unavailable.

let me know whether or not this is a bad idea, or if anything I just typed was incorrect. Cheers.

**Comment by Builderb0y** [comment]
1. Adding vanilla tags to big globe's biomes would only make modded structures spawn, not modded features, and the structures would almost certainly spawn incorrectly. I know from experience.
2. The better way is to make data packs for each mod you want to support.
3. The documentation I have written so far can be found in the [docs](https://github.com/Builderb0y/BigGlobe/tree/scriptable-generators/docs) folder.
4. My discord server re-opened when I released V4.6.0. Go check modrinth again for the invite.

Tags are not a magic solution for mod compatibility. If there was a magic solution, I'd've implemented it by now.

**Comment by IanuReeves** [comment]
gotcha, that makes sense. Thanks for the documentation! Ill look more into it.
(and thanks for letting me know about the discord link. Really appreciate it)
