### ISSUE TITLE
laggs blocks in the big globe worlds

### ISSUE THREAD

**Issue by MottiDowerro** [Builderb0y/BigGlobe#71]
I have only three mods installed: big globe latest version, sodium latest version and fabric api also latest version. When I break blocks, they update with a delay, as if I remain phantom for some time. This bug does not exist if you remove the sodium, or play in a non-big globe world. I tried installing different combinations of optimization mods, but it didn't help.

![image](https://github.com/user-attachments/assets/d71f2476-4b08-452f-b53b-d81740a2c973)

https://github.com/user-attachments/assets/8cb8c586-808b-40dc-943e-b21360b3a64d

**Comment by Builderb0y** [comment]
Confirmed, though less noticeable on my particular computer. Nevertheless, I was able to trace it back to my custom block coloring code. I tint blocks based on noise, not biome, and I made the noise more complex in the most recent version without realizing it. That's taking longer to run than it did in previous versions, which causes delays in blocks appearing and disappearing. I'll re-simplify it in the next version.

**Comment by MottiDowerro** [comment]
> Confirmed, though less noticeable on my particular computer. Nevertheless, I was able to trace it back to my custom block coloring code. I tint blocks based on noise, not biome, and I made the noise more complex in the most recent version without realizing it. That's taking longer to run than it did in previous versions, which causes delays in blocks appearing and disappearing. I'll re-simplify it in the next version.

yep, in 4.6.0 version all is good

**Comment by Builderb0y** [comment]
I'd prefer to keep this open until a proper fix is released.

**Comment by Builderb0y** [comment]
Fixed in V4.8.0.
