### ISSUE TITLE
generation bug

### ISSUE THREAD

**Issue by MottiDowerro** [Builderb0y/BigGlobe#72]
i think its not okay
![image](https://github.com/user-attachments/assets/adcce493-6149-4062-9460-b9b6a2056303)

**Comment by Builderb0y** [comment]
Minecraft doesn't do block updates as part of worldgen, which can cause a lot of issues similar to this. I've added a new check to remove double blocks manually in V4.8.0. Not all features have this check, but this bug should at least be less common now.
