### ISSUE TITLE
Exception occurred in netty pipeline

### ISSUE THREAD

**Issue by AmeriBaha** [Builderb0y/BigGlobe#73]
I have this error when I install mods on my server with mods "created" have you already had this problem?, is there a solution? and is it "serious" if the message "spam" the console?

`[13:06:00] [Netty Epoll Server IO #1/ERROR]: Exception occurred in netty pipeline
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer`

Thx

**Comment by Builderb0y** [comment]
Gonna need more information than that. Are you getting disconnected from the server? Is it crashing? Is there a full stack trace?

**Comment by AmeriBaha** [comment]
It does this when no one is on the server (development server) but I noticed in games a small "lag/cut" and the chests remain open unless I reboot the server.

I also noticed that this only happens with certain mods like Create (the most obvious) and the server is in fresh install (no one connects to the server)

I am testing with BG version 4.7.0 and version 4.50 (which I prefer for water generation) ^^

I would like to give you more details but the server only shows me this error line.

**Comment by Builderb0y** [comment]
Certainly a bit odd, but I don't think any of those things could be triggered by big globe. Just sounds like generic networking issues to me. And without any stack trace, there's nothing I can look into in detail.

**Comment by AmeriBaha** [comment]
I did tests over several days to determine which "mods" were causing this "bug" and when I "disable" BigGlobe the problem seems to be fixed... that's why I came to see if you might have a solution.

I would like to give you more examples or "logs" but the server only shows me that...

**Comment by Builderb0y** [comment]
Maybe it's just a side effect of the server struggling for bandwidth?

**Comment by AmeriBaha** [comment]
This is a development server and I just "set up" and no one has connected to the server yet.

And I have a good speed on the "dev" server https://www.speedtest.net/result/c/634e8b0f-5b6c-4604-b6af-f79638222cd5

and in my config the only thing I have changed is > "network-compression-threshold=512"

**Comment by Builderb0y** [comment]
That's really strange then. That server is a lot faster than my own home internet connection, and I don't know why the server would be struggling for bandwidth when no one is online. Big globe does very little with networking, and all of said networking only applies to players that are actively connected to the server.

**Comment by AmeriBaha** [comment]
Possible, I will test with another server.

If this changes anything I will come and tell you. ^^

**Comment by AmeriBaha** [comment]
I tested on another server and had the same problem, but you gave me a clue and I tried to modify "network-compression-threshold" from 512 to 256 and that seems to have solved the problem.

Thanks again for your help.

**Comment by Builderb0y** [comment]
Glad you got it fixed!
