### ISSUE TITLE
stutters in big globe world

### ISSUE THREAD

**Issue by MottiDowerro** [Builderb0y/BigGlobe#74]
when playing in big globe generation, I observe a huge number of stutters and FPS drops, while the world is generated well and very quickly.. I don’t know what could be the reason, but when I turn it off multithreading in modernfix mod, absolutely all friezes disappear, but the server starts to slow down a lot

**Comment by Builderb0y** [comment]
If all of your CPU cores are constantly in-use, then the client thread will struggle to find the resources required to run at its target speed. What aspect(s) of minecraft does modernfix's multithreading option affect? Big globe already uses multithreading for many parts of its worldgen by default.

**Comment by MottiDowerro** [comment]
> If all of your CPU cores are constantly in-use, then the client thread will struggle to find the resources required to run at its target speed. What aspect(s) of minecraft does modernfix's multithreading option affect? Big globe already uses multithreading for many parts of its worldgen by default.

I think this setting disables some kind of multithreading, but it does not affect the generation of the world... I don’t quite understand the reason, I’ll look into it

**Comment by MottiDowerro** [comment]
![image](https://github.com/user-attachments/assets/47cf70bd-5500-4a42-9177-985b63b6e725)
only with this mods stutters too.... only with big globe...

**Comment by MottiDowerro** [comment]
> If all of your CPU cores are constantly in-use, then the client thread will struggle to find the resources required to run at its target speed. What aspect(s) of minecraft does modernfix's multithreading option affect? Big globe already uses multithreading for many parts of its worldgen by default.

stutters occur when loading chunks

**Comment by Builderb0y** [comment]
Loading from disk, or generating new chunks? Chunk loading is a single-threaded process AFAIK. Chunk generation on the other hand is multi-threaded in big globe worlds. I already reserve 2 threads for the client and the server when doing multi-threaded generation, so if that's not enough, idk what would be.

**Comment by MottiDowerro** [comment]
> Loading from disk, or generating new chunks? Chunk loading is a single-threaded process AFAIK. Chunk generation on the other hand is multi-threaded in big globe worlds. I already reserve 2 threads for the client and the server when doing multi-threaded generation, so if that's not enough, idk what would be.

only with new chunks.... this is very noticeable when playing with shaders

**Comment by MottiDowerro** [comment]
> Loading from disk, or generating new chunks? Chunk loading is a single-threaded process AFAIK. Chunk generation on the other hand is multi-threaded in big globe worlds. I already reserve 2 threads for the client and the server when doing multi-threaded generation, so if that's not enough, idk what would be.


https://github.com/user-attachments/assets/ea2b1ea2-e54d-4140-858c-c813bed24a7c

after 12 seconds stuttering begins with new chunks

**Comment by Builderb0y** [comment]
V4.8.3 adds a new config option to tweak the number of threads big globe uses for worldgen tasks. See if reducing that helps at all.

**Comment by MottiDowerro** [comment]
> V4.8.3 adds a new config option to tweak the number of threads big globe uses for worldgen tasks. See if reducing that helps at all.

how do stream settings in sodium affect big globe worlds?

**Comment by MottiDowerro** [comment]
> If all of your CPU cores are constantly in-use, then the client thread will struggle to find the resources required to run at its target speed. What aspect(s) of minecraft does modernfix's multithreading option affect? Big globe already uses multithreading for many parts of its worldgen by default.

i tried change number of threads and its works! i have ryzen 5 5500 with 6 cores /12 threads and best value is 5-6 threads. by default big globe set value to 10!!!!

**Comment by Builderb0y** [comment]
Glad you found a good number to use!
