### ISSUE TITLE
Switch to fabric-api mod ID for clarity

### ISSUE THREAD

**Issue by Poopooracoocoo** [Builderb0y/BigGlobe#76]
You're using the outdated `fabric` ID for Fabric API. Fabric API still "provides" the `fabric` mod ID for compatibility, but it's not clear what it is so you should use the `fabric-api` mod ID. 

Ref. https://github.com/Builderb0y/BigGlobe/blob/scriptable-generators/src/main/versions/1.20.1/resources/core/fabric.mod.json#L33

https://github.com/Builderb0y/BigGlobe/blob/scriptable-generators/src/main/versions/1.21.1/resources/core/fabric.mod.json#L33

**Comment by Builderb0y** [comment]
Done in V4.8.3.
