### ISSUE TITLE
updating from 4.8.2 to 4.8.3 breaks 4.5.0 datapacks?

### ISSUE THREAD

**Issue by DurekuRyuu** [Builderb0y/BigGlobe#80]
I'm a little fried while I'm submitting this, apologies.

In updating from 4.8.2 to 4.8.3 it seems the datapacks for 4.5.0 are now breaking?

[(DP 0.1.2 big globe update) latest.log](https://github.com/user-attachments/files/18142441/DP.0.1.2.big.globe.update.latest.log)
[crash-2024-12-15_16.34.31-client.txt](https://github.com/user-attachments/files/18142442/crash-2024-12-15_16.34.31-client.txt)
[Big Globe.json](https://github.com/user-attachments/files/18142457/Big.Globe.json)

Here are my logs and big globe config, I tried to open an old world, which it reported that datapacks were causing issues and suggested launching it in safe mode. 
Afterwards I tried recreating the world, as that's what i've been doing to generate prospective worlds for my server featuring this, incrementing the filename and seed by 1 each time, and that just failed before even opening the world creation menu.
With that not working, I tried generating a new one, and that crashed my game before it even got into the menu.

Here's hoping you can make sense of these logs, I'll be taking a look at it again tomorrow when my brain has re-wrinkled itself into working again.

**Comment by Builderb0y** [comment]
There's so many errors in that log that I'm not sure which ones I should be paying attention to. But I did fix some issues with loading data packs in V4.8.4 just now. Try that version and see if it works for you.

**Comment by Builderb0y** [comment]
I'm gonna assume that silence means 4.8.4 works correctly.
