### ISSUE TITLE
Help me , not support other mod

### ISSUE THREAD

**Issue by rfrsdsdfds** [Builderb0y/BigGlobe#82]
Hello dear developer. I immediately apologize for the clumsy English is not my native language. I'm interested to know if you've done the support for third-party mods, I really want to use your mod to generate big globe, but all the remasters and mods for the new structures, and in general, the new mod content, which is ore structures and generation, does not work completely. I'll be waiting for an answer because the mod is really beautiful and all the biomes are beautifully made.

**Comment by Builderb0y** [comment]
You will need a data pack for each mod you want support for. Some data packs have already been made for some mods, others haven't been made yet. The data packs which have been made so far can be found on modrinth, and in my discord server.
